### ISSUE TITLE
Create and Verify PCB Design in EAGLE

### ISSUE THREAD

**Issue by kylehl** [UCI-UAVForge/Avionics#100]
Prerequisite Issues: #98  
Followup Issues: TBD
Related Issues: TBD

### Summary
- We will utilize EAGLE PCB design software in order to create a digital layout of the circuits we have researched in the prerequisite task.

### Terminal Objectives
- Create and verify a PCB design in EAGLE software of your respective circuit.

### Enabling Objectives
- Install educational version of [EAGLE here (scroll to the bottom).](https://cadsoft.io/pricing/)
- Learn and understand basic features of the software in order to complete your design.
- Verify your design using [EAGLE tools](https://learn.sparkfun.com/tutorials/using-eagle-board-layout/checking-for-errors).
- Comment on this task with a PDF output of your design in EAGLE.

**Comment by tuanal** [comment]
BEC Circuit 
[BEC schematic n pcb.pdf](https://github.com/UCI-UAVForge/Avionics/files/582863/BEC.schematic.n.pcb.pdf)

**Comment by uavforge** [comment]
[This might help](https://learn.sparkfun.com/tutorials/using-eagle-schematic) anyone who is having trouble with EAGLE.

**Comment by kngor** [comment]
Vin Circuit (Still needs to be improved A LOT)
https://docs.google.com/a/uci.edu/document/d/10MHJcWvOPGfbkg1CBGCSjKUfcz_O4dLCmFWjMkPsb1A/edit?usp=sharing

**Comment by wesleyw3** [comment]
Still needs more work
[https://docs.google.com/document/d/1kQQZKYufZkOKCrQZs1SLdn_OzSFqK-wY4GKI15Qoj8Y/edit]

**Comment by uavforge** [comment]
Task suspended until further notice.
