### ISSUE TITLE
Integrate Test LiDar with Arduino

### ISSUE THREAD

**Issue by haritdesai** [UCI-UAVForge/Avionics#110]
## Summary

Use Arduino Library to interface between Arduino and LiDar via I2C. Should be straightforward with library, will need to determine wiring. 

Arduino LiDar Lite V3 Information:
https://github.com/garmin/LIDARLite_v3_Arduino_Library

- Read Me has product page and spec doc linked

**Comment by Kentster82** [comment]
Can read accurate values from the Lidar.

**Comment by kylehl** [comment]
Finished task, merged with base master.
