### ISSUE TITLE
DC-DC Converter Design

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#19]
Once a selection has been made for task #9, go through and read the data sheet for the part. There will be a reference circuit and respective equations for the components in the circuit. Use those equations to calculate the values for all components in the circuit for 3.3V and 12V. Use only the worst case values in the circuit so that the converter can be used for any voltage in 3.3V-12V range.

Deliverable for this item: A circuit diagram of the DC-DC converter with external components and all of their values (in Altium Designer). Equations and calculations with work shown (in Mathematica). 

Estimated time for this item: 4 Hours

**Comment by tuanal** [comment]
am I suppose to use Altium Designer to draw the circuit? and for the calculations I just have to plug in numbers for the reference equations right?

**Comment by alihashemi2002** [comment]
@tuanal Yes for now just do calculations. Draw your circuit in LTSpice. I'm having a hard time finding Altium that you guys can download.

**Comment by vincentyuehzetran** [comment]
Tuan Lam & Vincent Tran LT3514 Calculations from Datasheet 

![lt3514 calculations p1](https://cloud.githubusercontent.com/assets/15068426/10812426/599400ac-7dd3-11e5-854b-4cbcf58bcbc8.JPG)
![lt3514 calculations p2](https://cloud.githubusercontent.com/assets/15068426/10812427/59a518c4-7dd3-11e5-96bf-0e25c0179476.JPG)

**Comment by tuanal** [comment]
Tuan Lam & Vincent Tran: LT3514 circuit diagram. 
We are not sure what to put for Rload's but other components should be filled out with the calculations. 

![lt3514](https://cloud.githubusercontent.com/assets/15115868/10812309/066b9f26-7dd2-11e5-8851-95ff5071afda.png)

**Comment by tuanal** [comment]
Fixed Calculations 

![12218132_1061066010610816_1691852905_o](https://cloud.githubusercontent.com/assets/15115868/11010607/e3387820-8494-11e5-903b-373c49a8db95.jpg)
![12209118_1061066000610817_399525271_o](https://cloud.githubusercontent.com/assets/15115868/11010608/e3388252-8494-11e5-9e24-5fa164109b10.jpg)

**Comment by tuanal** [comment]
Fixed Circuit Diagram

![lt3514](https://cloud.githubusercontent.com/assets/15115868/11010610/f7849106-8494-11e5-9cfc-ba4fa74a8954.jpg)

**Comment by alihashemi2002** [comment]
File with calculations will be uploaded to the repo. Thanks
