### ISSUE TITLE
DC-DC Converter Component Selection

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#20]
Once tasks #19 and #21 are complete, find surface mount components for the circuit. Use www.digikey.com as your source for the parts. Follow these guidelines:

Resistors:
Accuracy: 1%
Temperature Coefficients: 100ppm or better

Capacitors: 
Accuracy: 20%
Temperature Coefficients: X7R or better 

Inductors:
Follow guidelines from DC-DC converter datasheet

Footprints:
MAKE SURE that the footprint for each component matches what is used on the development board which is found in task #22 

**These values may be different from the calculated values and that is fine. Select the values that are the closest match to the calculations. If need be, go back to the simulation in task #21 for this circuit and check whether parts of higher or lower value will give you the closest output to the calculated values**

Deliverable for this item: Excel spreadsheet of all parts required. Send this to Ali so he can order the parts.

Estimated time for this item: 1 Hour

**Comment by kngor** [comment]
I'm still working on finding the right parts, there are a few capacitors I was unable to locate by looking only at ceramic capacitors. I highlighted the ones I was unable to find in red. Also, for the inductors what conditions do you want me to check for?

https://docs.google.com/spreadsheets/d/1EM1cx0cTfXoWlTEZjdQJYvgM8UdsE0vW98CMMddBUA4/edit?usp=sharing

**Comment by alihashemi2002** [comment]
@kngor Great job on the first go around. A few of the parts need to be changed, but this was a very very good start. Lets meet at the start of the winter quarter to hash out the details. Thanks, Kendrick!

**Comment by jason-watkins** [comment]
This issue should be reevaluated and assigned a new milestone or closed as appropriate.

**Comment by alihashemi2002** [comment]
Closing this task since the scope of the project has changed. We are going to focus further on the autopilot rather than a digitally controlled power supply.
