### ISSUE TITLE
DC-DC Converter Design Verification

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#21]
Once task #19 is complete, run the following simulations in LTSpice:

Transient response for 3ms
DC Bias Point when the circuit is under a 3A load. (Output voltage/3 = Rload)

Deliverable for this item: Graph of all 4 outputs versus time in a Word document.

Estimated time for this item: 2 Hours

**Comment by jason-watkins** [comment]
This issue should be reevaluated and assigned a new milestone or closed as appropriate.

**Comment by alihashemi2002** [comment]
Closing this task since the scope of the project has changed. We are going to focus further on the autopilot rather than a digitally controlled power supply.
