### ISSUE TITLE
DC-DC Converter Evaluation Board

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#22]
Once task #9 is complete, contact the manufacturer or check www.digikey.com or www.mouser.com, etc. and order the evaluation board for the DC-DC converter. 

Deliverable for this item: send a link to Ali so he can order the part. 

Estimated time for this item: 0.5 Hours

**Comment by steveocho** [comment]
It seems like there are two very slightly different types. The only difference between the 2 is the package. I am not sure of the importance of the package and why it matters so I'll post two links.

$7.49
http://www.digikey.com/product-detail/en/LT3514EUFD%23PBF/LT3514EUFD%23PBF-ND/4134883

$8.01
http://www.digikey.com/product-detail/en/LT3514EFE%23PBF/LT3514EFE%23PBF-ND/4356510

**Comment by tuanal** [comment]
@steve: try this
https://www.arduino.cc/en/Main/Software

**Comment by alihashemi2002** [comment]
@steveocho those are the bare chips. Look for the evaluation board.

**Comment by steveocho** [comment]
Here's the evaluation board:
http://www.digikey.com/product-search/en/programmers-development-systems/evaluation-boards-dc-dc-ac-dc-off-line-smps/2622539?k=lt3514

**Comment by alihashemi2002** [comment]
@steveocho thanks.
