### ISSUE TITLE
Output Filter Component Selection

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#23]
Once the circuit in task #12  is complete, find through-hole AND surface mount (so they can be breadboard-ed and soldered on the PCB) components for the circuit. Use www.digikey.com as your source for the parts. Follow these guidelines:

Resistors:
Accuracy: 1%
Temperature Coefficients: 100ppm or better
Surface Mount Size: 0603 or 0805

Capacitors: 
Accuracy: 20%
Temperature Coefficients: X7R or better 
Surface Mount Size: 0603 or 0805

Inductors:
Accuracy: 20%
Max Current: 4A min
Saturation Current: 3A min
Surface Mount Size: 0603, 0805, or 1206

**For surface mount components, please make sure that they follow the sizing requirements above. For through-hole components, make sure they are axial or radial (only have two pins). Please also take a look at cost. More than likely, if you have a part that costs more than $1 for 1 piece, it isn't the right part!

** Please make sure parts are IN STOCK. You can ensure you are searching for in stocks parts only by checking the "in stock" button in the search parameters. 

**These values may be different from the calculated values and that is fine. Select the values that are the closest match to the calculations. If need be, go back to the simulation for this circuit and check whether parts of higher or lower value will give you the closest output to the calculated values**

Deliverable for this item: Excel spreadsheet of all parts required. Send this to Ali so he can order the parts.

Estimated time for this item: 1 Hour

**Comment by steveocho** [comment]
I don't know if you wanted one for  inductor as well but I included one (1% Accuracy). Both the inductor and the capacitor are 100 micro units. Attached is the excel file showing both the digi-key and the manufacturer part numbers. Let me know if you need anything else.
[OutputFilterComponents.xlsx](https://github.com/UCI-UAVForge/Avionics/files/27634/OutputFilterComponents.xlsx)

**Comment by jason-watkins** [comment]
This issue should be reevaluated and assigned a new milestone or closed as appropriate.

**Comment by alihashemi2002** [comment]
Closing this task since the scope of the project has changed. We are going to focus further on the autopilot rather than a digitally controlled power supply.
