### ISSUE TITLE
DC-DC Converter Output Noise Measurement (Before & After Filter)

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#24]
Once tasks #20 , #21 #22, and #23 have been completed, setup the evaluation for 3.3V. Remove the parts on the evaluation board and re-solder the correct components that were purchased based off of the calculation. Connect an oscilloscope to the output of the converter and measure the noise. Noise in this case will be a ripple voltage with amplitude in the mV range. 

Next, breadboard the filter circuit that was designed in #12. Connect its input to the output of the converter. Measure the output noise one more time. 

Repeat this test for the converter set for 12V out. 

Deliverable for this item: screenshots of the output waveform before adding the filter and after adding the filter for 3.3V output and for 12V output.

Estimated time for this item: 3 Hours

**Comment by jason-watkins** [comment]
This issue should be reevaluated and assigned a new milestone or closed as appropriate.

**Comment by alihashemi2002** [comment]
Closing this task since the scope of the project has changed. We are going to focus further on the autopilot rather than a digitally controlled power supply.
