### ISSUE TITLE
Output Digital Switch Selection

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#27]
Search for a NMOS transistor with the following specs:

Logic Level (3.3V OR 5V at gate should turn it on)
Current Rating: 7A or greater
Size: as small as possible

Deliverable for this item: part number and data sheet

Estimated time for this item: 1 Hour

**Comment by vincentyuehzetran** [comment]
RFD7N10LE
[RFD7N10LE.pdf](https://github.com/UCI-UAVForge/Avionics/files/15533/RFD7N10LE.pdf)

**Comment by alihashemi2002** [comment]
@vincentyuehzetran perfect, thanks
