### ISSUE TITLE
Current Measurement IC Evaluation Board

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#30]
Research and find an evaluation board for the INA219. This IC is used to measure current draw for a particular supply. We will be using it to monitor the current draw of each of our DC-DC converters. 

Deliverable for this item: link for purchase sent to Ali

Estimated time for this item: 1 Hour

**Comment by vincentyuehzetran** [comment]
http://www.ti.com/tool/ina219evm#buy

Is it this board?

**Comment by alihashemi2002** [comment]
@vincentyuehzetran thanks dude. That is it.
