### ISSUE TITLE
Current Measurement IC Code

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#31]
Read the datasheet for the TI INA219 that is attached. We need to read the output current and power dissipation from this device. The device will have many settings you need to configure as well. We are going to have a maximum Vin+ - Vin- of 320mV and a maximum current of 3A through each device. Use that information to configure the device in your code. Also, remember that we have 3 of these devices in our circuit. You will have to look in the data sheet and see what the i2c ID can be set to if 3 devices are used.

Deliverable for this item: code that configures all 3 INA219, reads current and power from each device and outputs it to a variable in firmware. 

Estimated time for this item: 6 Hours

[ina219.pdf](https://github.com/UCI-UAVForge/Avionics/files/13348/ina219.pdf)

**Comment by jason-watkins** [comment]
This issue should be reevaluated and assigned a new milestone or closed as appropriate.

**Comment by alihashemi2002** [comment]
Closing this task since the scope of the project has changed. We are going to focus further on the autopilot rather than a digitally controlled power supply.
