### ISSUE TITLE
Current Measurement IC Testing

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#32]
Once tasks #30 and #31 are complete, setup the evaluation board so that a current of 2A is flowing through it. This can be done using a resistor and a power supply (V=IR). Look at the example circuits in the datasheet to see how to connect the resistor and power supply to the evaluation board. Remember to power the evaluation board using a separate supply so that the board isn't also measuring its own usage. Upload your code to the arduino, connect it to the evaluation board via i2c and test your programming. 

Deliverable for this item: screenshot of readings of the chip sent back to your computer and documentation of how you used the provided software

Estimated time for this item: 2 Hours

**Comment by jason-watkins** [comment]
This issue should be reevaluated and assigned a new milestone or closed as appropriate.

**Comment by alihashemi2002** [comment]
Closing this task since the scope of the project has changed. We are going to focus further on the autopilot rather than a digitally controlled power supply.
