### ISSUE TITLE
Digital Potentiometer Code

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#33]
Write code that does the following in function form:

1. Takes two inputs: resistance value (100-100k ohms) and pot number (1-4) 
2. Calculates the required digital value to send to the pot (using equation in datasheet)
3. Writes the calculated value to the specified pot number

Notes:
Pot number is either pot 1,2,3,4. These will be the same as the 4 'RDAC' values in the datasheet resembled by 3 bits. Use the equation for Rwa, set that equal to the resistance value that a user inputs to the function, solve for Dw and send that value to the corresponding pot register. For our part, RAB=100kOhms. 

Deliverable for this item: Code that implements the above function in the arduino environment

Estimated time for this item: 2 Hours

[AD5204_5206.pdf](https://github.com/UCI-UAVForge/Avionics/files/13322/AD5204_5206.pdf)

**Comment by SpacePirate** [comment]
Hey @alihashemi2002,

I am using the equation in the datasheet:
Rwa = (256-Dx)/256 * Rab + Rw

Here, what is Rw?

**Comment by jason-watkins** [comment]
This issue should be reevaluated and assigned a new milestone or closed as appropriate.

**Comment by alihashemi2002** [comment]
Closing this task since the scope of the project has changed. We are going to focus further on the autopilot rather than a digitally controlled power supply.
