### ISSUE TITLE
Setting Output Voltage Code

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#34]
Write code that implements the following as a function:

1. Takes two inputs: a number that is either 3.3V, 5V, 9V, or 12V and a number between 1-4. The first number is the desired output voltage and the second number is the supply they want to change the voltage of.  
2. Calculates the resistance required for that output voltage using voltage output equation in the data sheet of the part chosen in #9. (R1 will be set to 1k ohms).
3. Plug the number found in step 2 into the equation for resistance setting in the data sheet for #33. 
4. Write the number found in 3 to the corresponding potentiometer. 

Deliverable for this item: a code that implements all of the above in a single function with two inputs in the arduino environment. 

Estimated time for this item: 3 Hours

**Comment by steveocho** [comment]
Which program are we using to code? I think wesley asked this question on another issue as well. #1 makes it seems like we do this in arduino because we are assigning inputs into a pin. However, #2 says to calculate. I don't think Arduino can crunch numbers.

**Comment by alihashemi2002** [comment]
Arduino. Everything is on it. Of course it can!

**Comment by jason-watkins** [comment]
This issue should be reevaluated and assigned a new milestone or closed as appropriate.

**Comment by alihashemi2002** [comment]
Closing this task since the scope of the project has changed. We are going to focus further on the autopilot rather than a digitally controlled power supply.
