### ISSUE TITLE
Learn Differences Between Capacitors

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#43]
Please watch the following videos on capacitors. It is very important to know the differences between the 3 major kinds of capacitors when doing component selection. You MUST know when to use which type.

https://www.youtube.com/watch?v=xlvqUts9H9c
https://www.youtube.com/watch?v=TDDoi70cxw0

Estimated time for this task: 1 Hour

**Comment by jason-watkins** [comment]
This issue should be reevaluated and assigned a new milestone or closed as appropriate.

**Comment by alihashemi2002** [comment]
Closing this task since the scope of the project has changed. We are going to focus further on the autopilot rather than a digitally controlled power supply.
