### ISSUE TITLE
Powersupply Firmware

### ISSUE THREAD

**Issue by jason-watkins** [UCI-UAVForge/Avionics#52]
Prerequisite Issues: None
Followup Issues: TBD
Related Issues: See "scope: power supply firmware" label
### Summary

Assist hardware team in developing firmware for the UAV power suppply.
### Terminal Objective
- Working power supply for the UAVForge quadcopter.
### Enabling Objectives

TBD

**Comment by haritdesai** [comment]
Barbara: Test firmware for Current Monitor, Gyro, and Compass. 

All sensors are I2C, can test all at the same time, route power through Arduino in parallel. Write firmware to produce meaningful output with the Arduino.

**Comment by barbarm** [comment]
- Already tested firmware for current monitor and ultrasonic sensor separately

- Currently working on merging the two test codes for these sensors so that current monitor can output voltage and current through the ultrasonic sensor

- End goal is to connect all sensors at once

**Comment by uavforge** [comment]
Great work, will move on with integration into main system next quarter. - Kyle
