### ISSUE TITLE
RF Systems Analysis

### ISSUE THREAD

**Issue by jason-watkins** [UCI-UAVForge/Avionics#53]
Prerequisite Issues: None
Followup Issues: TBD
Related Issues:

### Summary
Research and test the suitability of various unlicensed RF bands for UAV conrol.

### Terminal Objective
* Brief (~2000 words) paper describing your findings

### Enabling Objectives
TBD

**Comment by kylehl** [comment]
Closed, Radio/Comms is looking into RF solutions.
