### ISSUE TITLE
Interface Between LIDAR Sensor and Arduino Due

### ISSUE THREAD

**Issue by jason-watkins** [UCI-UAVForge/Avionics#54]
Prerequisite Issues: None
Followup Issues: #64, #65
Related Issues: None

### Summary
Implement a module that collects raw data from the LIDAR sensor and publishes that data to the data management module.

### Terminal Objective
* Data from the LIDAR sensor published to the data management system.

### Enabling Objectives
* Establish a communication link between the LIDAR and Due (See #64)
* Read data from the LIDAR (See #65)
* Format raw LIDAR data in a way that is easy to consume for other services
* Publish well formed LIDAR data to the data management system

**Comment by kylehl** [comment]
Finally committed the master and slave code between Due (slave) and Uno (master). Needs more testing and modification before it is complete.
