### ISSUE TITLE
Pixhawk Communications - Execute Code

### ISSUE THREAD

**Issue by jason-watkins** [UCI-UAVForge/Avionics#57]
Prerequisite Issues: #56
Followup Issues:
Related Issues: #47

### Summary
Execute custom code on the Pixhawk.

### Terminal Objectives
* Add a custom module to the Pixhawk environment that outputs data over any output port

### Enabling Objectives
* Add a custom module to the Pixhawk environment that outputs any data (e.g. "Hello World") on a repeating basis
* Rebuild the Pixhawk environment with your custom module
* Upload the compiled code to the Pixhawk
* Verify that your code works by reading the output data

**Comment by jason-watkins** [comment]
https://pixhawk.org/dev/start contains information about writing code for the Pixhawk

**Comment by inistar** [comment]
April 15: Found example code we can use to connect to all UART ports with a hello message. Need connect Arduino and Pixhawk, but don't have the right wires.

**Comment by kylehl** [comment]
Closing off old issue - finished
