### ISSUE TITLE
Pixhawk Data - Execute Code

### ISSUE THREAD

**Issue by jason-watkins** [UCI-UAVForge/Avionics#60]
Prerequisite Issues: #59
Followup Issues:
Related Issues: #48

### Summary
Execute custom code on the Pixhawk.

### Terminal Objectives
* Add a custom module to the Pixhawk environment that outputs data over any output port

### Enabling Objectives
* Add a custom module to the Pixhawk environment that outputs any data (e.g. "Hello World") on a repeating basis
* Rebuild the Pixhawk environment with your custom module
* Upload the compiled code to the Pixhawk
* Verify that your code works by reading the output data

**Comment by jason-watkins** [comment]
https://pixhawk.org/dev/start contains information about writing code for the Pixhawk

**Comment by kylehl** [comment]
Closing off old issues - finished
