### ISSUE TITLE
Sensor 2 - Research and Select New Sensor

### ISSUE THREAD

**Issue by jason-watkins** [UCI-UAVForge/Avionics#68]
Prerequisite Issues: None
Followup Issues: TBD
Related Issues: #55

### Summary
Research and select a type of sensor that would be useful to have. Assemble a list of sensors available for purchase.

### Terminal Objective
* Purchase a new sensor for the quadcopter

### Enabling Objectives
* Select a type of sensor
* Research available sensors that can be purchased
* Select the best sensor within the project budget
* I will submit a purchase request for the sensor

**Comment by steveocho** [comment]
For this one, I'll look into the accelerometer sensor.
