### ISSUE TITLE
Research and Select GPS

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#71]
Prerequisite Issues: None
Followup Issues: TBD
Related Issues: None
### Summary

Research and select an I2C or SPI GPS to use on the custom autopilot
### Terminal Objective
- Design and purchase the GPS for the quadcopter custom autopilot
### Enabling Objectives
- Research the possibility of using a differential GPS (2 sensors, one on the UAV and one on the ground station)
- Research to determine the resolution required for the sensor (what is the smallest change in angle that would be useful for us to detect?)
- Do all necessary calculations for the circuit design of sensor as well as any necessary external components
- Select the best sensor within the project budget
- I will submit a purchase request for the sensor

**Comment by noelcopter** [comment]
Ali please check this out, let me know what you think
https://www.u-blox.com/sites/default/files/products/documents/NEO-6_DataSheet_(GPS.G6-HW-09005).pdf

**Comment by noelcopter** [comment]
it needs I2C-GPS NAV MODULE

**Comment by alihashemi2002** [comment]
@Noelcopter the chip looks really good! Have you checked into differential GPS? Also, what specs did you decide to design around? Or most importantly, what accuracy/precision did you decide the GPS should provide?

**Comment by noelcopter** [comment]
@alihashemi2002 The previous GPS is not available through their store anymore we must get it from the third party. The new generation is more precise GPS (Neo 7P, High precision GNSS < 1 m) which supports DGPS, low power consumption with very high sensitivity and also supports the maximum speed of 500m/s which is way more than we need (14m/s). The price is $119.00. 
https://www.u-blox.com/sites/default/files/products/documents/NEO-7P_DataSheet_(UBX-13003787).pdf

If we want to downgrade a bit the next one will be Neo M8N which does not support differential GPS and its accuracy is 2m. The price on this GPS is $69.00.
https://www.u-blox.com/sites/default/files/NEO-M8_DataSheet_(UBX-13003366).pdf

**Comment by noelcopter** [comment]
Differential correction

http://www.trimble.com/gps_tutorial/dgps-where.aspx

**Comment by noelcopter** [comment]
DGPS site configuration
http://www.navcen.uscg.gov/?pageName=dgpsSiteInfo&bySite

**Comment by alihashemi2002** [comment]
@noelcopter Thanks! Any additional information that we need to know in regards to using the differential GPS with the coast guard?

**Comment by kylehl** [comment]
On hold - priorities are elsewhere for hardware for now.
