### ISSUE TITLE
Research and Select Barometer

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#72]
Prerequisite Issues: None
Followup Issues: TBD
Related Issues: None

### Summary
Research and select and select an I2C or SPI barometer to use on the custom autopilot.

### Terminal Objective
* Purchase and design the barometer for the quadcopter custom autopilot

### Enabling Objectives
* Research to determine the resolution required for the sensor (what is the smallest change in angle that would be useful for us to detect?)
* Do all necessary calculations for the circuit design of sensor as well as any necessary external components
* Select the best sensor within the project budget
* I will submit a purchase request for the sensor

**Comment by kngor** [comment]
[Barometer.pdf](https://github.com/UCI-UAVForge/Avionics/files/159647/Barometer.pdf)

**Comment by exolete** [comment]
[Task72-Barometer.pdf](https://github.com/UCI-UAVForge/Avionics/files/160223/Task72-Barometer.pdf)

**Comment by alihashemi2002** [comment]
@kngor @exolete guys, can you please do me a favor to see if you can find anything that will go up to 120 C operating temperature? I know it wasn't apart of the requirements but if you could please look I'd appreciate it!

Thanks

**Comment by exolete** [comment]
[Barometer (3).pdf](https://github.com/UCI-UAVForge/Avionics/files/164298/Barometer.3.pdf)

**Comment by alihashemi2002** [comment]
@exolete thanks
