### ISSUE TITLE
Research and Select Magnatometer

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#74]
Prerequisite Issues: None
Followup Issues: TBD
Related Issues: None

### Summary
Research and determine if the autopilot would benefit from having magnetometer information. If so do further research and select an I2C or SPI magnetometer.

### Terminal Objective
* Determine if a magnetometer is necessary for the quadcopter. If one is, design and purchase the magnetometer for the quadcopter custom autopilot

### Enabling Objectives
* Research need for a magnetometer for quadcopter autopilots
* If the sensor is required research to determine the resolution required for the sensor (what is the smallest change in magnetism that would be useful for us to detect?)
* Do all necessary calculations for the circuit design of sensor as well as any necessary external components
* Select the best sensor within the project budget
* I will submit a purchase request for the sensor

**Comment by vanessazin** [comment]
Hi Ali,

Hope the quarter has been going well so far!! From all these emails, seems like UAV is on a roll! That's awesome! So proud of you guys! However I was wondering if you can please take me off the email list. I do not think I'll be joining this quarter. Thank you so much! Good luck! Definitely rooting for you guys and the success that is to come with this project.

Best,
Vanessa Zin

**Comment by alihashemi2002** [comment]
Hi Vanessa:

Hope all is well. Sorry for the email spam. Please un-follow our repository
and it will fix the issue. If it doesn't feel free to email me again.

Thanks,
Ali

On Sun, Jan 10, 2016 at 2:47 AM, vanessazin <notifications@github.com>
wrote:

> Hi Ali,
>
> Hope the quarter has been going well so far!! From all these emails, seems
> like UAV is on a roll! That's awesome! So proud of you guys! However I was
> wondering if you can please take me off the email list. I do not think I'll
> be joining this quarter. Thank you so much! Good luck! Definitely rooting
> for you guys and the success that is to come with this project.
>
> Best,
> Vanessa Zin
>
> Sent from my iPhone
>
> > On Jan 9, 2016, at 10:24 PM, Ali Hashemi <notifications@github.com>
> wrote:
> >
> > Prerequisite Issues: None
> > Followup Issues: TBD
> > Related Issues: None
> >
> > Summary
> >
> > Research and determine if the autopilot would benefit from having
> magnetometer information. If so do further research and select an I2C or
> SPI magnetometer.
> >
> > Terminal Objective
> >
> > Determine if a magnetometer is necessary for the quadcopter. If one is,
> design and purchase the magnetometer for the quadcopter custom autopilot
> > Enabling Objectives
> >
> > Research need for a magnetometer for quadcopter autopilots
> > If the sensor is required research to determine the resolution required
> for the sensor (what is the smallest change in angle that would be useful
> for us to detect?)
> > Do all necessary calculations for the circuit design of sensor as well
> as any necessary external components
> > Select the best sensor within the project budget
> > I will submit a purchase request for the sensor
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCI-UAVForge/Avionics/issues/74#issuecomment-170333630>
> .
>



-- 
Best,
Ali Hashemi
Team Lead--Avionics | UAV Forge
Electrical Engineering Major
University of California, Irvine
C: (949)-338-8698
E: SAHashe1@UCI.edu

**Comment by tuanal** [comment]
quick question: what is the project budget for this sensor, found 1 for roughly $15.

**Comment by tuanal** [comment]
Link to the Magnetometer sensor, including schematic, data sheet and tutorial.
Sparkfun HMC5883L ($14.95): https://www.sparkfun.com/products/10530

LIS3MDL (~$6) : http://www.ebay.com/itm/like/321958197317?ul_noapp=true&chn=ps&lpid=82 
Datasheet for LIS3MDL: http://www.st.com/web/en/resource/technical/document/datasheet/DM00075867.pdf


Notes taken on magnometer: https://drive.google.com/folderview?id=0B1o-BQLmbOo5NFhaQkNLWERMalk&usp=sharing

**Comment by alihashemi2002** [comment]
@tuanal I like the LIS3MDL. Nice chip. What were the specs you decided to design around?

What are your resolution and accuracy? How many sensors do you think are necessary?

**Comment by tuanal** [comment]
I'll look at the datasheet one more time tonight and i'll have some info for you tomorrow.

**Comment by tuanal** [comment]
[Magnetometersresearch.pdf](https://github.com/UCI-UAVForge/Avionics/files/119751/Magnetometersresearch.pdf)

**Comment by alihashemi2002** [comment]
@tuanal awesome, looks great, thank you!
