### ISSUE TITLE
Research and Select Wireless Communication Method

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#76]
Prerequisite Issues: None
Followup Issues: TBD
Related Issues: None
### Summary

Research and determine the best form of wireless communications for the link between the UAV and the ground station
### Terminal Objective
- Design and purchase the communications method and IC for the UAV
### Enabling Objectives
- Research the different forms of wireless communications methods and select the best fit for our UAV project based on the following:
  - Range [3 Miles min]
  - Power Usage [500mW max]
  - Antenna Size [prefer external antenna]
  - Cost
  - Frequency (prefer ISM Band [900MHz or less])
- Research to find the necessary requirements for the above criteria and speak to R&D team if necessary for sizing and range requirements
- Find an IC that meets the above requirements and communicates with I2C, SPI, or other wired protocol
- A development board for the TI CC series of transceivers will work well for this application. Use this as a starting (or ending) point.  
- Do all necessary calculations for the circuit design of chip as well as any necessary external components (this includes an impedance matching network for the antenna, if necessary)
- Design a test PCB with communication and antenna headers that can be used to test code and performance
- I will order the PCB and all necessary parts

**Comment by exolete** [comment]
[WirelessCommunications.pdf](https://github.com/UCI-UAVForge/Avionics/files/170273/WirelessCommunications.pdf)

**Comment by exolete** [comment]
[Wireless Communications (Update).docx](https://github.com/UCI-UAVForge/Avionics/files/245585/Wireless.Communications.Update.docx)

**Comment by uavforge** [comment]
Task suspended until further notice.
