### ISSUE TITLE
Additional Sensor Integration - Sonar

### ISSUE THREAD

**Issue by kylehl** [UCI-UAVForge/Avionics#82]
Prerequisite Issues: None
Followup Issues: TBD
Related Issues: None

### Summary
Research and work with R&D to determine additional sensors that would be useful to have on the UAV and integrate those sensors with the data management system.

### Terminal Objective
* Determine a useful sensor that the UAV does not currently have
* Data from that sensor published to the data management system.

### Enabling Objectives
* Establish a communication link between the new sensor and Due
* Read data from the new sensor
* Format raw sensor data in a way that is easy to consume for other services
* Publish well formed sensor data to the data management system

**Comment by kylehl** [comment]
@howardl2 will float between this task and task #85 (mainly concentrating on Pixhawk integration). @Osmius will also be working on this task alongside Howard.

**Comment by Osmius** [comment]
Managed to find out how the new sonar sends data to the Due. I'm currently figuring out how to format the data from the sensor.

**Comment by kylehl** [comment]
Successfully read and formatted data from sonar to the Arduino Due.
