### ISSUE TITLE
Research H Bridge Circuit

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#89]
Prerequisite Issues: None
Followup Issues: TBD
Related Issues: #77 
### Summary

Design a circuit to act as the H-Bridge for the ESCs
### Terminal Objective
- Design a circuit for the ESCs that will drive the motor
### Enabling Objectives
- Research how H-Bridge works
- Decide whether it is best to buy a chip or to use a custom circuit
- If lumped components are used to design a circuit, simulate it in LTSpice and post pictures of the output voltage/current
- Pick either a chip to use or lumped components from Digi-Key
- Once components are picked, ask @tuanal to import the parts into Altium

**Comment by alihashemi2002** [comment]
@kngor is the second assigned person to the task.

**Comment by vincentyuehzetran** [comment]
@kngor  check this out: http://www.instructables.com/id/H-Bridge-on-a-Breadboard/

**Comment by kngor** [comment]
[Buy H Bridges.pdf](https://github.com/UCI-UAVForge/Avionics/files/298595/Buy.H.Bridges.pdf)

**Comment by kngor** [comment]
@alihashemi2002 Here is a document explaining why we chose to go with a premade H-bridge setup and other options if the first one cannot be used.
