### ISSUE TITLE
Pixhawk/Arduino - Read/Write Sensor Data using SPI

### ISSUE THREAD

**Issue by kylehl** [UCI-UAVForge/Avionics#93]
Prerequisite Issues: #92 
Followup Issues: TBD
Related Issues: #47 #48 #85 
### Summary

After attempting to connect Pixhawk to Arduino system using UART, we will attempt a secondary method by using SPI as our serial communication protocol.
### Terminal Objectives
- Send Pixhawk data to Arduino Due and receive data as necessary using SPI. Finish implementation by reading and writing meaningful sensor data instead of dummy discrete data.
### Enabling Objectives
- Add a custom module to the Pixhawk environment that outputs sensor data on a repeating basis using SPI
- Rebuild the Pixhawk environment with your custom module
- Upload the compiled code to the Pixhawk
- Verify that your code works by reading the output data
- Write Arduino SPI code for Due to receive data properly and pass to data management

**Comment by haritdesai** [comment]
Suspended until further notice - SPI will be attempted again if necessary.
